### ISSUE TITLE
Data modeling task

### ISSUE THREAD

**Issue by brandomr** [jataware/dojo#168]
## Dojo Data Modeling

This issue is to create a backend capability to process the user directives from the data modeling HMI and to generate corresponding dataset(s) in Dojo based on those directives. At a high level, within the HMI the user will select various NetCDF file features, combine them in novel ways, and generate a corresponding DAG that represents their data modeling pipeline. This pipeline can be represented as a JSON payload that instructs the pipeline on a set of actions. Once completed, these actions imply the creation of >=1 new dataset in Dojo.

## Tasks

- [x] complete JSON payload specification for data modeling tasks
  - [x]  add `name` and `description` to `save` nodes
  - [x]  create Elasticsearch index for data models (and corresponding pydantic model?)
  - [x] create CRUD endpoints for data model objects
- [x] add Dojo endpoint for `/process_data_model/{data_model_id}` which, for a given `data_model_id` kicks off an RQ processing job
  - >Note: naming conventions throughout this issue are entirely notional
- [x] Name DAGPipes (or keep the name!) and package it and push it to PyPi
- [x] Add DAGPipes pipeline processing `pip` package to [`tasks/tasks/requirements.txt`](https://github.com/jataware/dojo/blob/main/tasks/tasks/requirements.txt)
- [x] create RQ worker task in `tasks/tasks/data_modeling.py` that takes in a `data_model_id` and:
  a) fetches relevant `data_model` JSON from ES. See [this example](https://github.com/jataware/dojo/blob/main/tasks/tasks/paragraph_embeddings_processors.py#L14C1-L15C27) for pulling the `data_model` from ES (e.g. instantiating an ES object inside the task)
  b) fetches relevant NetCDF files as prescribed by the data model's `load` nodes. See this [example from Elwood task](https://github.com/jataware/dojo/blob/main/tasks/tasks/elwood_processors.py#L146-L161) for stub on how to fetch the NetCDF from S3. [`get_rawfile`](https://github.com/jataware/dojo/blob/main/tasks/tasks/utils.py#L64) utility is probably helpful here too.
  c) runs pipeline processing code and generates `output` NetCDF file(s)
  d) for each `output`, create a `dataset` in Dojo
    - >Note: see below for more detail on this 
  e) cleanup file system and remove no longer needed NetCDF files

## Creating `datasets`

To create a `dataset` for each output as indicated in d) above we should investigate the most streamline way we can possibly put the `dataset` into Dojo. Since we do need to perform Elwood transformations on these NetCDF we have a couple options:

1. We could do all the backend file processing, S3 `puts`, etc and create the appropriate objects to hand jam into ES behind the scenes
2. We could leverage (and complete?) our data registration via data dictionary methodology and leverage only Dojo APIs for creating the datasets
3. We could take some kind of hybrid approach where we create the `dataset` via Dojo's APIs but perform the underlying data transformations "manually" with Elwood under the hood inside the RQ task.

I think this is a key discussion point for this week, but does not prevent us from getting started on the other key tasks outlined in this issue.

## Getting data for example scenario

- [x] Get gridded asset wealth dataset registered to Dojo
- [x] Ensure relevant data, e.g. MODIS, wealth and CMIP scenario of demo-interest are registered to Dojo

**Comment by adamgilg** [comment]
An example of the annotation response from `/indiators/{id}/annotations` with a simple dataset:

```{
  "indicators": {
    "id": "27d2e4ec-ba65-4fab-8bae-3837fb94ff77",
    "name": "netcdf multiple features",
    "family_name": null,
    "description": "this has multiple features",
    "created_at": 1695048006969,
    "category": null,
    "domains": [],
    "maintainer": {
      "name": "test",
      "email": "test@test.com",
      "organization": "",
      "website": ""
    },
    "data_paths": [
      "s3://datasets/27d2e4ec-ba65-4fab-8bae-3837fb94ff77/27d2e4ec-ba65-4fab-8bae-3837fb94ff77.parquet.gzip",
      "s3://datasets/27d2e4ec-ba65-4fab-8bae-3837fb94ff77/27d2e4ec-ba65-4fab-8bae-3837fb94ff77_str.parquet.gzip"
    ],
    "outputs": [
      {
        "unit": "feat1",
        "is_primary": true,
        "name": "time",
        "description": "feat1",
        "alias": {},
        "unit_description": "",
        "display_name": "time",
        "type": "str",
        "data_resolution": {
          "temporal_resolution": "daily",
          "spatial_resolution": []
        },
        "ontologies": {}
      },
      {
        "unit": "feat2",
        "is_primary": true,
        "name": "X",
        "description": "feat2",
        "alias": {},
        "unit_description": "",
        "display_name": "X",
        "type": "float",
        "data_resolution": {
          "temporal_resolution": "daily",
          "spatial_resolution": []
        },
        "ontologies": {}
      },
      {
        "unit": "feat3",
        "is_primary": true,
        "name": "Y",
        "description": "feat3",
        "alias": {},
        "unit_description": "",
        "display_name": "Y",
        "type": "float",
        "data_resolution": {
          "temporal_resolution": "daily",
          "spatial_resolution": []
        },
        "ontologies": {}
      },
      {
        "unit": "feat4",
        "is_primary": true,
        "name": "d_flood",
        "description": "feat4",
        "alias": {},
        "unit_description": "",
        "display_name": "d_flood",
        "type": "float",
        "data_resolution": {
          "temporal_resolution": "daily",
          "spatial_resolution": []
        },
        "ontologies": {}
      }
    ],
    "qualifier_outputs": [
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "datetime",
        "description": "test",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "datetime",
        "type": "datetime",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "country",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "country",
        "type": "country",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "admin1",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "admin1",
        "type": "admin1",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "admin2",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "admin2",
        "type": "admin2",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "admin3",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "admin3",
        "type": "admin3",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "lat",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "lat",
        "type": "lat",
        "ontologies": {}
      },
      {
        "unit": null,
        "related_features": [
          "time",
          "X",
          "Y",
          "d_flood"
        ],
        "name": "lng",
        "description": "location",
        "unit_description": null,
        "qualifier_role": "breakdown",
        "display_name": "lng",
        "type": "lng",
        "ontologies": {}
      }
    ],
    "tags": [],
    "geography": {
      "country": [],
      "admin1": [],
      "admin2": [],
      "admin3": []
    },
    "period": {
      "gte": 1420840800000,
      "lte": 1420070400000
    },
    "deprecated": false,
    "data_sensitivity": "",
    "data_quality": "",
    "published": true,
    "fileData": {
      "raw": {
        "uploaded": true,
        "url": "samplenetcdf.nc",
        "rawFileName": "raw_data.nc"
      }
    },
    "temporal_resolution": "daily",
    "data_paths_normalized_robust": [
      "s3://datasets/normalized/27d2e4ec-ba65-4fab-8bae-3837fb94ff77/27d2e4ec-ba65-4fab-8bae-3837fb94ff77_normalized_robust.parquet.gzip"
    ],
    "data_paths_normalized": [
      "s3://datasets/normalized/27d2e4ec-ba65-4fab-8bae-3837fb94ff77/27d2e4ec-ba65-4fab-8bae-3837fb94ff77_normalized.parquet.gzip"
    ],
    "feature_names": [
      "time",
      "X",
      "Y",
      "d_flood"
    ]
  },
  "annotations": {
    "metadata": {
      "transformations": null,
      "files": {
        "raw_data.nc": {
          "filetype": "netcdf",
          "filename": "samplenetcdf.nc",
          "rawFileName": "raw_data.nc"
        }
      },
      "histograms": {
        "datetime": null,
        "X": {
          "bins": [
            36.3,
            36.6933333333,
            37.0866666667,
            37.48,
            37.8733333333,
            38.2666666667,
            38.66,
            39.0533333333,
            39.4466666667,
            39.84,
            40.2333333333
          ],
          "values": [
            102384,
            102384,
            102384,
            93852,
            102384,
            102384,
            93852,
            102384,
            102384,
            102384
          ]
        },
        "d_flood": {
          "bins": [
            0,
            0.0000205446,
            0.0000410892,
            0.0000616338,
            0.0000821784,
            0.000102723,
            0.0001232676,
            0.0001438122,
            0.0001643568,
            0.0001849014,
            0.000205446
          ],
          "values": [
            1006542,
            44,
            47,
            88,
            7,
            9,
            13,
            10,
            9,
            7
          ]
        },
        "Y": {
          "bins": [
            -3.5733333333,
            -3.31,
            -3.0466666667,
            -2.7833333333,
            -2.52,
            -2.2566666667,
            -1.9933333333,
            -1.73,
            -1.4666666667,
            -1.2033333333,
            -0.94
          ],
          "values": [
            101952,
            101952,
            101952,
            101952,
            89208,
            101952,
            101952,
            101952,
            101952,
            101952
          ]
        },
        "time": null
      },
      "geotime_classify": {
        "datetime": {
          "format": "%Y-%m-%d %H:%M:%S",
          "type_inference": "str",
          "category": "time",
          "subcategory": "date"
        },
        "time": {
          "format": null,
          "type_inference": "str",
          "category": "time",
          "subcategory": "date"
        }
      },
      "column_statistics": {
        "datetime": {
          "top": "2015-01-01 00:00:00",
          "unique": 108,
          "count": 1006776,
          "freq": 9322
        },
        "X": {
          "std": 1.1451197237,
          "25%": 37.2749287749,
          "min": 36.3,
          "max": 40.2333333333,
          "mean": 38.2666666667,
          "75%": 39.2584045584,
          "count": 1006776,
          "50%": 38.2666666667
        },
        "d_flood": {
          "std": 0.0000013154,
          "25%": 0,
          "min": 0,
          "max": 0.000205446,
          "mean": 1.78e-8,
          "75%": 0,
          "count": 1006776,
          "50%": 0
        },
        "Y": {
          "std": 0.7698624215,
          "25%": -2.9318803419,
          "min": -3.5733333333,
          "max": -0.94,
          "mean": -2.2566666667,
          "75%": -1.5814529915,
          "count": 1006776,
          "50%": -2.2566666667
        },
        "time": {
          "top": "0 days 00:00:00",
          "unique": 108,
          "count": 1006776,
          "freq": 9322
        }
      }
    },
    "annotations": {
      "geo": [],
      "date": [
        {
          "date_type": "date",
          "time_format": "%Y-%m-%d %H:%M:%S",
          "aliases": {},
          "primary_date": true,
          "qualifies": [],
          "name": "datetime",
          "description": "test",
          "display_name": "datetime",
          "type": "date"
        }
      ],
      "feature": [
        {
          "feature_type": "str",
          "aliases": {},
          "qualifies": [],
          "units_description": "",
          "qualifierrole": "breakdown",
          "name": "time",
          "description": "feat1",
          "units": "feat1",
          "display_name": "time",
          "type": "feature"
        },
        {
          "feature_type": "float",
          "aliases": {},
          "qualifies": [],
          "units_description": "",
          "qualifierrole": "breakdown",
          "name": "X",
          "description": "feat2",
          "units": "feat2",
          "display_name": "X",
          "type": "feature"
        },
        {
          "feature_type": "float",
          "aliases": {},
          "qualifies": [],
          "units_description": "",
          "qualifierrole": "breakdown",
          "name": "Y",
          "description": "feat3",
          "units": "feat3",
          "display_name": "Y",
          "type": "feature"
        },
        {
          "feature_type": "float",
          "aliases": {},
          "qualifies": [],
          "units_description": "",
          "qualifierrole": "breakdown",
          "name": "d_flood",
          "description": "feat4",
          "units": "feat4",
          "display_name": "d_flood",
          "type": "feature"
        }
      ]
    }
  }
}

**Comment by adamgilg** [comment]
An example of the Data Modeler JSON structure generated by the frontend/React Flow.
Note: this will change slightly when I add the `geo/time resolution column` to it. 

```

{
  "nodes": [
    {
      "type": "load",
      "data": {
        "label": "load",
        "input": "d_flood::83de4099-ed1a-4a35-a204-4cb58bede279"
      },
      "id": "n_1f7288b5-b8bf-4194-bdb0-66913706ee8e"
    },
    {
      "type": "load",
      "data": {
        "label": "load",
        "input": "X::27d2e4ec-ba65-4fab-8bae-3837fb94ff77"
      },
      "id": "n_ee1ad582-83d6-4683-b4b2-fb53c0117928"
    },
    {
      "type": "country_split",
      "data": {
        "label": "country_split",
        "input": [
          "United States",
          "Canada"
        ]
      },
      "id": "n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e"
    },
    {
      "type": "threshold",
      "data": {
        "label": "threshold",
        "input": {
          "value": "",
          "type": "greater_than"
        }
      },
      "id": "n_1b2c94af-216b-4654-ae29-8de5198ba835"
    },
    {
      "type": "multiply",
      "data": {
        "label": "multiply"
      },
      "id": "n_3a823027-59fe-4324-b639-fc4f1c11ec71"
    },
    {
      "type": "sum",
      "data": {
        "label": "sum",
        "input": {
          "lat": false,
          "lon": false,
          "time": true,
          "country": false,
          "scenario": true,
          "realization": false
        }
      },
      "id": "n_5a705b11-8287-47cb-b3f3-1ea6daa5e1b7"
    },
    {
      "type": "save",
      "data": {
        "label": "save",
        "input": ""
      },
      "id": "n_833e39c4-e081-41ea-b457-921705ca7176"
    }
  ],
  "edges": [
    {
      "source": "n_1f7288b5-b8bf-4194-bdb0-66913706ee8e",
      "target": "n_1b2c94af-216b-4654-ae29-8de5198ba835",
      "id": "reactflow__edge-n_1f7288b5-b8bf-4194-bdb0-66913706ee8e-n_1b2c94af-216b-4654-ae29-8de5198ba835"
    },
    {
      "source": "n_1b2c94af-216b-4654-ae29-8de5198ba835",
      "target": "n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e",
      "id": "reactflow__edge-n_1b2c94af-216b-4654-ae29-8de5198ba835-n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e"
    },
    {
      "source": "n_ee1ad582-83d6-4683-b4b2-fb53c0117928",
      "target": "n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e",
      "id": "reactflow__edge-n_ee1ad582-83d6-4683-b4b2-fb53c0117928-n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e"
    },
    {
      "source": "n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e",
      "target": "n_3a823027-59fe-4324-b639-fc4f1c11ec71",
      "id": "reactflow__edge-n_b7a59e5c-b6cd-4806-8f67-b03c80b16a9e-n_3a823027-59fe-4324-b639-fc4f1c11ec71multiply-handle-1"
    },
    {
      "source": "n_ee1ad582-83d6-4683-b4b2-fb53c0117928",
      "target": "n_3a823027-59fe-4324-b639-fc4f1c11ec71",
      "id": "reactflow__edge-n_ee1ad582-83d6-4683-b4b2-fb53c0117928-n_3a823027-59fe-4324-b639-fc4f1c11ec71multiply-handle-2"
    },
    {
      "source": "n_3a823027-59fe-4324-b639-fc4f1c11ec71",
      "target": "n_5a705b11-8287-47cb-b3f3-1ea6daa5e1b7",
      "id": "reactflow__edge-n_3a823027-59fe-4324-b639-fc4f1c11ec71-n_5a705b11-8287-47cb-b3f3-1ea6daa5e1b7"
    },
    {
      "source": "n_5a705b11-8287-47cb-b3f3-1ea6daa5e1b7",
      "target": "n_833e39c4-e081-41ea-b457-921705ca7176",
      "id": "reactflow__edge-n_5a705b11-8287-47cb-b3f3-1ea6daa5e1b7-n_833e39c4-e081-41ea-b457-921705ca7176"
    }
  ]
}

**Comment by ccjoel** [comment]
Data Modeling Demo working. Closing.
